<Project Sdk="Microsoft.NET.Sdk">
<ItemGroup>
  <PackageReference Include="itext7" Version="8.0.2" />
</ItemGroup>
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
<ItemGroup>
  <PackageReference Include="ExcelDataReader" Version="3.7.0" />
  <PackageReference Include="ExcelDataReader.DataSet" Version="3.7.0" />
</ItemGroup>
</Project>
